### ISSUE TITLE
下滑到最底部的时候 导致webview抖动?

### ISSUE THREAD

**Issue by XiongKe94** [Tijn1314/NestedScrollWebView#2]
下滑最底部到页面抖动

最新版本

**Comment by XiongKe94** [comment]
https://github.com/tobiasrohloff/NestedScrollWebView

这个库就不存在这个问题

**Comment by Tijn1314** [comment]
我看到了 web页面加载高度未固定的时候出现的问题，跟网页相关

**Comment by XiongKe94** [comment]
怎么可以修复呢？

**Comment by Tijn1314** [comment]
这个主要是当前页面跳转url以后，存的历史值没有清理 我有空了看一下吧

**Comment by Tijn1314** [comment]
if (expectScroll < 0) {
                        unconsumedY = expectScroll;
                        scrolledDeltaY = oldY;
                    } else if (expectScroll > range) {
//                        unconsumedY = range - expectScroll;
                        scrolledDeltaY = expectScroll - range;
                    }

注释的那一句就行  但是我看关联滑动的问题 我再看看

**Comment by Tijn1314** [comment]
或者用最新版
